### ISSUE TITLE
merge transcript fails if none of the input transcripts contain any CDS

### ISSUE THREAD

**Issue by hargup** [yeban/afra#86]
This happens because these lines:

[Ln 667-671 EditTrack.js](https://github.com/yeban/afra/commit/5405644556923db5643cb128c08d51a614d5a0c1#diff-c25ec4577d64be6ef33135f5bd230ca9R671)
```js
        var translationStart = _.map(transcripts, _.bind(function (transcript) {
            return this.getTranslationStart(transcript);
        }, this));
        translationStart = (strand === -1) ? _.max(translationStart) : _.min(translationStart);
```
The `_.min` and `_.max` function returns `Infinity` and `-Infinity` if the input array contains only `undefined`. I think this is no the expect behavior of underscore, hence I reported the issue at https://github.com/jashkenas/underscore/issues/1997. Nevertheless we have change our code to handle the issue.

* * *
The issue can be reproduced with the following transcripts
```JSON
    {"data": {
        "end": 25,
        "start": 1,
        "strand": 1,
        "subfeatures": [
            {
                "data": {
                    "end": 13,
                    "start": 1,
                    "strand": 1,
                    "type": "exon"
                }
            },
            {
                "data": {
                    "end": 25,
                    "start": 16,
                    "strand": 1,
                    "type": "exon"
                }
            }
        ],
        "type": "transcript"
    },
    "normalized": true,
};
```
```JSON
    {"data": {
        "end": 25,
        "start": 1,
        "strand": 1,
        "subfeatures": [
            {
                "data": {
                    "end": 13,
                    "start": 1,
                    "strand": 1,
                    "type": "exon"
                }
            }
        ],
        "type": "transcript"
    },
    "normalized": true,
};
```
on the refSeq:
```
 TCATCCTCGTCTTTCTTTTTATTGTACTATTAATAGTGCTGTTGA
```

**Comment by yeban** [comment]
@hargup I couldn't verify that `mergeTranscripts` fails if input transcripts don't have a CDS. But I can confirm and have resolved the issue that `translationStart` is set to `Inifnity` (in [L776]( https://github.com/yeban/afra/blob/master/www/JBrowse/View/Track/EditTrack.js#L776)) if transcripts don't have CDS. Please can you verify that this issue is not resolved?

**Comment by hargup** [comment]
@yeban I can verify that the issue is fixed now. Thanks.
